[[permission]]
identifier = "owlnest-swarm"
description = """Full permission of the swarm"""
commands.allow = [
    "plugin:owlnest-swarm|listen",
    "plugin:owlnest-swarm|dial",
    "plugin:owlnest-swarm|get_local_peer_id",
    "plugin:owlnest-swarm|list_connected",
    "plugin:owlnest-swarm|list_listeners",
    "plugin:owlnest-swarm|get_peer_info",
    "plugin:owlnest-swarm|disconnect_peer"
]
